### ISSUE TITLE
UNMET PEER DEPENDENCY firebase@4.0.0

### ISSUE THREAD

**Issue by zoharyosef** [angular/angularfire2#1011]
### Version info

**Angular:** 4

**Firebase:** 4 

**AngularFire:** 4.0.0-rc.0

### How to reproduce these conditions

simply trying to install with

npm install firebase angularfire2 --save

gives me this
![image](https://cloud.githubusercontent.com/assets/6332377/26558937/fbe9515a-44b4-11e7-8824-d16477c921c4.png)

and this
![image](https://cloud.githubusercontent.com/assets/6332377/26558830/5dcab55e-44b4-11e7-9642-72cf8028ca03.png)

### Expected behavior

I want it to work

### Actual behavior
It doesn't work :(

BTW Thanks guys you're awesome :)

**Comment by bblanke** [comment]
I'm in the same boat!

**Comment by zoharyosef** [comment]
Well, it works alright when following the [installation & setup](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) guide step by step.
Only happened when I tried adding it to the angular 4 starter project.

**Comment by davideast** [comment]
We'll have this fixed in the next day or so. Hold tight and watch #999 for updates.

**Comment by PeterDavidCarter** [comment]
Any progress? Can confirm this is still an issue with Firebase version 4.1.1.
