### ISSUE TITLE
ApplicationRef.isStable never goes to "true" when an instance of AngularFireAuth is injected

### ISSUE THREAD

**Issue by pglazkov** [angular/angularfire2#1347]
When `AngularFireAuth` is injected anywhere on the page, the `ApplicationRef.isStable` never emits `true`. This causes problems with latest `@angular/service-worker`, which relies on `ApplicationRef.isStable` to install the worker. This probably also would cause server-side rendering to timeout, but I didn't test this.

### Version info

**Angular:** 5.0.0

**Firebase:** 4.6.2

**AngularFire:** 5.0.0-rc4

### How to reproduce these conditions

Inject `AngularFireAuth` into a component and subscribe to the `ApplicationRef.isStable` observable:

```ts
import { Component, ApplicationRef, ChangeDetectorRef } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  constructor(appRef: ApplicationRef, af: AngularFireAuth) {    
    appRef.isStable.subscribe(s => {
      console.log(s); 
    });
  }
}
```
Here is a project that reproduces the problem: https://stackblitz.com/edit/angularfire2-appref-isstable
### Expected behavior

The `ApplicationRef.isStable` observable should emit `true` shortly after application is loaded.

### Actual behavior

The `ApplicationRef.isStable` observable emits only initial `false` value.

**Comment by jamesdaniels** [comment]
I'm actually tackling right now. Thanks for the report!

**Comment by jamesdaniels** [comment]
Once patched I'll cut a new RC.

**Comment by playground** [comment]
I have a somewhat different issue, seems like return ApplicationRef; never got executed.

I'm new to angularfire2, can someone offer some good use cases for using angularfire2?

**Comment by deftomat** [comment]
The same issue when I injects `AngularFirestore`.

**Comment by LanderBeeuwsaert** [comment]
jep, same issue here.

**Comment by val-samonte** [comment]
I am having the same issue when injecting AngularFirestore

**Comment by patrickmichalina** [comment]
Any updates on this issue?

**Comment by Splaktar** [comment]
I am seeing this as well. It is being tracked in https://github.com/angular/angular/issues/20970 where I added a [full reproduction repo](https://github.com/angular/angular/issues/20970#issuecomment-354977288) on GitHub.

**Comment by ArtDesire** [comment]
seems like angularfire uses @firebase/auth which is not supported in angular.*
firebase auth or firebase module itself should be initialized outside angular(ngZone.runOutsideAngular())

@firebase/auth utilizes timers which stall app from emitting Stable result.
https://github.com/angular/angular/issues/8089#issuecomment-214098366

**Comment by Splaktar** [comment]
From @JiaLiPassion  "`firebase auth` make a very very long `setTimeout` to do proactive token refresh. (more than `200000ms`)". Based on this [comment](https://github.com/angular/angular/issues/8089#issuecomment-214098366), AngularFire2 needs to be doing something like [this](https://github.com/angular/angular/issues/20970#issuecomment-353093686) when running this long `setTimeout`.

I'm not sure how we could disable Firebase Auth from doing this so that AngularFire2 could do it in an Angular-friendly way, but this will be a problem for integration testing as well as Service Worker registration. @jamesdaniels is anyone on the Firebase team able to look into this?

**Comment by ArtDesire** [comment]
angularfire2 cannot leave RC stage until this is fixed.

**Comment by jamesdaniels** [comment]
Fixed in rc7

**Comment by PierreDuc** [comment]
The issue persists in the Auth module. 

After you login some `setTimeout` is set at 33000ms. The code is too obfuscated to pinpoint where it exactly comes from except from `auth.js` from firebase.

By using a so called `TaskTrackingZoneSpec`, I was able to determine that when this zone task is created, the `NgZone.isInAngularZone()` returns true, and the e2e tests will timeout. 

When I put this inside the `onScheduleTask` of the trackingZone:

    if (task.type === 'macroTask' && task.data.delay > 3200000 && task.data.delay < 3400000) {
      setTimeout(() => {
        Zone.current.cancelTask(task);
      });
    }`

The tests will run fine, because that particular task is no longer blocking the stable state of the angular zone, but also that task no longer exists, and I don't know how important it is ;).

Apparently some calls inside the `AngularfireAuthModule` trigger this timeout to run inside the zone. I haven't figured out which one exactly yet. My best guess is that it has something to do with the IdToken, judging by the stack trace

**Comment by PierreDuc** [comment]
After a little more digging I found that the problem is originating from the [`fireauth.AuthUser.prototype.initializeProactiveRefreshUtility_`](https://github.com/firebase/firebase-js-sdk/blob/0997040b6a231e54cbc2d6f8c293a78e83451220/packages/auth/src/authuser.js#L456). 

This is at least triggered on login with using just email and password, or by using the `getIdToken()` and setting `forceRefresh` to true.

For now the workaround is whenever you call these functions is to wrap it inside a `ngZone.runOutsideAngular` -> `ngZone.run`

**Comment by PierreDuc** [comment]
Just talking with myself here, I manged to work around it by having to override the [`AngularFireAuth`](https://github.com/angular/angularfire2/blob/master/src/auth/auth.ts#L70) like this:

    { provide: AngularFireAuth, useClass: AngularFireOwnAuth },

And have this:

```
@Injectable()
class AngularFireOwnAuth extends AngularFireAuth {
  readonly idToken: Observable<string | null>;

  constructor(
     @Inject(FirebaseOptionsToken) options: any,
     @Optional() @Inject(FirebaseNameOrConfigToken) nameOrConfig: string|any|undefined,
     @Inject(PLATFORM_ID) platformId: Object,
     zone: NgZone
  ) {
    super(options, nameOrConfig, platformId, zone);

    this.idToken = this.user.pipe(
      switchMap(async user =>
        user ? zone.run(async() => await zone.runOutsideAngular(() => user.getIdToken())) : null
      )
    );
  }
}
```

This will make sure the `getIdToken` is called outside the angular zone. If this is called inside the zone, it will trigger the long `setTimeout` and prevent angular from ever getting stable. At least not for 3300000ms :)

**Comment by epelc** [comment]
Thanks @PierreDuc! I can confirm the run outside zone method works as intended. I'm not using angular fire but it fixes it with `interval` from rxjs since it's the same idea.

**Comment by jamesdaniels** [comment]
Thanks for finding that problem. I had incorrectly assumed switchMap
would've stayed in the outer zone, I'll patch for the next RC.

**Comment by PierreDuc** [comment]
@jamesdaniels The problem is that the observable `this.user` is inside the zone. So any pipe from it will be in the zone as well. Besides having to override the service, I also had to make any call to the `AngularFireAuth`, which in turn can possibly trigger the `initializeProactiveRefreshUtility_` from firebase, to run outside the zone, and reenter after done.

I didn't have the time to figure out which of the calls trigger it, but I'm sure that at least `user.getIdToken` is a naughty one

**Comment by JiaLiPassion** [comment]
@PierreDuc, maybe the problem is `goog.Promise` is not `zone aware`? Could you provide a reproduce repo?

**Comment by PierreDuc** [comment]
@JiaLiPassion well, the issue is a long lasting `setTimeout`, triggered by firebase itself. This timeout is running inside the angular zone, and preventing the zone to be without `macroTasks`. Don't think that `goog.Promise` is involved here.

To reproduce a repo, I have to set-up a mock firebase app, where you can register and login. Don't think I have time soon to make something like that

**Comment by JiaLiPassion** [comment]
@PierreDuc , ok, I know about the `long lasting setTimeout` one. 
About the code here 

```javascript
if (task.type === 'macroTask' && task.data.delay > 3200000 && task.data.delay < 3400000) {
  setTimeout(() => {
    Zone.current.cancelTask(task);
  });
}`
```
Maybe there is a better way to solve this one, if this `long setTimeout` is not relevant to test, 
you can try this in `onScheduleTask`,

```javascript
onScheduleTask: (delegate, curr, target, task) => {
  if ( task.source === 'setTimeout' && task.data.delay > 3200000 && task.data.delay < 3400000) {
      task.cancelScheduleRequest();
      task = Zone.root.scheduleTask(task);
      return task;
  }
  return delegate.scheduleTask(target, task);
}
```

**Comment by PierreDuc** [comment]
@JiaLiPassion Ah, but that's just in an additional test class called a [`TaskTrackingZoneSpec`](https://github.com/angular/zone.js/blob/master/lib/zone-spec/task-tracking.ts), which I modified a bit to determine what was causing the hanging angular zone. 

But yes instead of overriding the AngularFireAuth, I could implement it like this, just in the e2e, although I don't really want something like this in my specs. It will make the e2e code different from the production code.

**Comment by JiaLiPassion** [comment]
@PierreDuc , got it, I believe in `Testability` there is an additional API to let you decide when to `done`, but anyway, it also use `TaskTrackingZoneSpec`. When you have time, if you can share your e2e code, maybe I can help to find out how to make it look better, because it maybe a common use case for using `zone` for test. Thanks.

**Comment by JeongJun-Lee** [comment]
This issue should be reopened. Angular9 + AngularFire6 has same issue.

**Comment by Splaktar** [comment]
@JeongJun-Lee it would be appropriate to open a new issue in that case.

You may want to look into https://angular.io/api/service-worker/SwRegistrationOptions as that allows you to register a SW without waiting for `isStable` to be `true`.

**Comment by yadimon** [comment]
i am developing a plugin to ignore such special async tasks.
https://www.npmjs.com/package/protractor-sync-options-plugin

https://github.com/angular/protractor/issues/4584#issuecomment-684487566

would be nice, if community supports me with pr and tests/issues for your use-cases.
