### ISSUE TITLE
RC4 install produces "Error: Metadata version mismatch for module angularfire2/index.d.ts, found version 4 expected 3, resolving symbol AppModule"

### ISSUE THREAD

**Issue by katowulf** [angular/angularfire2#1410]
This looks similar to #1397. I can create a complete repro if needed, but I've literally followed the install guide to the letter.

### Version info

```
Sputnik:test-af2 katowulf$ npm list | grep angular
├─┬ @angular/animations@4.4.6
├─┬ @angular/cli@1.4.9
│ ├─┬ @angular-devkit/build-optimizer@0.0.36
│ │ ├─┬ @angular-devkit/core@0.0.22
│ ├─┬ @schematics/angular@0.0.49
│ │ └─┬ @angular-devkit/core@0.0.20
├─┬ @angular/compiler@4.4.6
├─┬ @angular/compiler-cli@4.4.6
│ ├─┬ @angular/tsc-wrapped@4.4.6
├─┬ @angular/forms@4.4.6
├─┬ @angular/http@4.4.6
├── @angular/language-service@4.4.6
├─┬ @angular/router@4.4.6
├── angularfire2@5.0.0-rc.4

Sputnik:test-af2 katowulf$ npm list | grep fire
├── angularfire2@5.0.0-rc.4
├─┬ firebase@4.8.1
│ ├─┬ @firebase/app@0.1.5
│ │ ├── @firebase/app-types@0.1.0
│ │ └── @firebase/util@0.1.5
│ ├─┬ @firebase/auth@0.3.1
│ │ └── @firebase/auth-types@0.1.0
│ ├─┬ @firebase/database@0.1.6
│ │ ├── @firebase/database-types@0.1.0
│ │ ├── @firebase/util@0.1.5 deduped
│ ├─┬ @firebase/firestore@0.2.2
│ │ ├── @firebase/firestore-types@0.1.0
│ │ ├── @firebase/webchannel-wrapper@0.2.5
angularfire2@5.0.0-rc.4@schematics/angular@0.0.49
│ ├─┬ @firebase/messaging@0.1.6
│ │ ├── @firebase/messaging-types@0.1.0
│ │ └── @firebase/util@0.1.5 deduped
│ ├─┬ @firebase/polyfill@0.1.3
│ ├─┬ @firebase/storage@0.1.5
│ │ └── @firebase/storage-types@0.1.0
```

### How to reproduce these conditions

1. Follow setup steps described [in readme](https://github.com/angular/angularfire2/blob/master/docs/install-and-setup.md#1-installation-and-setup)
2. Run `ng serve` after installing AF2
3. Fails with errors described below.

### Debug output

** Errors in the JavaScript console **

This error appears upon running `ng serve` immediately after adding `AngularFireModule.initializeApp(environment.firebase),` into my app.module.ts and running `ng serve`

```
ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (5,45): Cannot find namespace 'firebase'.
ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (8,17): Cannot find namespace 'firebase'.
ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (9,21): Cannot find namespace 'firebase'.
ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (10,22): Cannot find namespace 'firebase'.
ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (11,20): Cannot find namespace 'firebase'.
ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (13,22): Cannot find namespace 'firebase'.
ERROR in Error: Metadata version mismatch for module /Users/katowulf/projects/test-af2/node_modules/angularfire2/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/katowulf/projects/test-af2/src/app/app.module.ts, resolving symbol AppModule in /Users/katowulf/projects/test-af2/src/app/app.module.ts, resolving symbol AppModule in /Users/katowulf/projects/test-af2/src/app/app.module.ts
    at syntaxError (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/katowulf/projects/test-af2/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/katowulf/projects/test-af2/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/katowulf/projects/test-af2/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

** Output from `firebase.database().enableLogging(true);` **

n/a

### Expected behavior

Should compile and start server when following install directions exactly.

### Actual behavior

Receive version mismatch in angularfire2/index.d.ts.

**Comment by katowulf** [comment]
Reverting to RC3 removes the "mismatch" error, but still produces these: 
`ERROR in /Users/katowulf/projects/test-af2/node_modules/angularfire2/firebase.app.module.d.ts (5,45): Cannot find namespace 'firebase'.`

**Comment by davideast** [comment]
Should be fixed with the current next release. `npm i angularfire2@next`.

**Comment by gauravweni** [comment]
Metadata version mismatch for module E:/fhc-app-temp/node_modules/angularfire2/index.d.ts, found version 4, expected 3

**Comment by BobaFett58** [comment]
@gauravweni try to 
' npm install angularfire2@5.0.0-rc.3 --save '

**Comment by davideast** [comment]
Fixed in the latest release.

**Comment by syncreticudon** [comment]
I think this error is back. Getting it on brand new project:
"angularfire2": "^5.0.0-rc.10",
"firebase": "^5.0.4",

**Comment by Vivek-abstract** [comment]
I'm getting this error in the 5.1.1 release. I have no idea how to fix it. I tried downgrading to 5.0.0.rc3 and rc4 but it didn't work
