### ISSUE TITLE
Node_modules/firebase/index"' has no exported member 'functions'.

### ISSUE THREAD

**Issue by naveen-me** [angular/angularfire2#1708]
Typescript Error
Module '"E:/nani/Andy/practo/myApp/node_modules/firebase/index"' has no exported member 'functions'.

please help me out 

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.2.9
Angular Compiler CLI: 5.2.9
Node: 8.11.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by jamesdaniels** [comment]
What version of Firebase + angularfire are you using?

**Comment by UnEpicFail** [comment]
Hello, i have the same trouble.

> Failed to compile.
node_modules/angularfire2/firebase.app.module.d.ts(5,54): error TS2694: Namespace '"/home/unepicfail/projects/roster/node_modules/firebase/app/index"' has no exported member 'app'.
node_modules/angularfire2/firebase.app.module.d.ts(8,26): error TS2694: Namespace "/home/unepicfail/projects/roster/node_modules/firebase/app/index"' has no exported member 'auth'.
node_modules/angularfire2/firebase.app.module.d.ts(9,30): error TS2694: Namespace '"/home/unepicfail/projects/roster/node_modules/firebase/app/index"' has no exported member 'database'.
node_modules/angularfire2/firebase.app.module.d.ts(10,31): error TS2694: Namespace '"/home/unepicfail/projects/roster/node_modules/firebase/app/index"' has no exported member 'messaging'.
node_modules/angularfire2/firebase.app.module.d.ts(11,29): error TS2694: Namespace '"/home/unepicfail/projects/roster/node_modules/firebase/app/index"' has no exported member 'storage'.
node_modules/angularfire2/firebase.app.module.d.ts(13,31): error TS2694: Namespace '"/home/unepicfail/projects/roster/node_modules/firebase/app/index"' has no exported member 'firestore'.

"firebase": "^5.0.4",
"angularfire2": "^5.0.0-rc.5-next",

**Comment by sagarpdev6** [comment]
Same issue with angularfire2 5.0.0 rc 10 and firebase 5.0.4

**Comment by albertvp** [comment]
+1

**Comment by TimGeerts** [comment]
I've got the same issues (had them a few weeks back, fixed it, have it again).

> ERROR in node_modules/angularfire2/firebase.app.module.d.ts(5,54): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'app'.
> node_modules/angularfire2/firebase.app.module.d.ts(8,26): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'auth'.
> node_modules/angularfire2/firebase.app.module.d.ts(9,30): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'database'.
> node_modules/angularfire2/firebase.app.module.d.ts(10,31): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'messaging'.
> node_modules/angularfire2/firebase.app.module.d.ts(11,29): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'storage'.
> node_modules/angularfire2/firebase.app.module.d.ts(13,31): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(8,52): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(9,55): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(9,89): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(10,58): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(10,104): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(10,149): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(10,191): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(11,58): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(11,103): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/changes.d.ts(11,139): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(8,63): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(8,105): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(10,28): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(12,31): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(12,78): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(13,36): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(14,34): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(15,39): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(16,36): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/collection/collection.d.ts(17,36): error TS2694: Namespace
> '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/document/document.d.ts(8,19): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/document/document.d.ts(9,31): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/document/document.d.ts(10,37): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/document/document.d.ts(14,51): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/firestore.d.ts(9,64): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/firestore.d.ts(12,34): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/interfaces.d.ts(4,20): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/interfaces.d.ts(5,23): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/interfaces.d.ts(14,46): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/interfaces.d.ts(14,89): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/interfaces.d.ts(16,19): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/interfaces.d.ts(17,21): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/observable/fromRef.d.ts(6,50): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/observable/fromRef.d.ts(6,89): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/observable/fromRef.d.ts(7,50): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/observable/fromRef.d.ts(7,107): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/observable/fromRef.d.ts(8,57): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.
> node_modules/angularfire2/firestore/observable/fromRef.d.ts(8,102): error TS2694: Namespace '"C:/Stuff/TiMo/node_modules/firebase/app/index"' has no exported member 'firestore'.

"firebase": "^5.0.4",
"angularfire2": "^5.0.0-rc.4"

**Comment by GuilhermeSanches** [comment]
I solved with these versions

  "firebase": "4.12.1",
  "rxjs": "5.5.10",
  "angularfire2": "^5.0.0-rc.6"

**Comment by TimGeerts** [comment]
"firebase": "4.5.0"
"angularfire2": "5.0.0-rc.4"
fixed it for me, for now

**Comment by albertvp** [comment]
Had to upgrade to ngx6 and cover backwards compatibility with rxjs-compat...
```
    "@angular/common": "^6.0.4",
    "@angular/compiler": "^6.0.4",
    "@angular/core": "^6.0.4",
    "@angular/forms": "^6.0.4",
    "@angular/platform-browser": "^6.0.4",
    "@angular/platform-browser-dynamic": "^6.0.4",
    "@ionic/storage": "2.1.3",
    "ajv": "^5.5.2",
    "angularfire2": "^5.0.0-rc.10",
    "firebase": "^5.0.4",
    "ionic-angular": "^3.9.2",
    "ionicons": "3.0.0",
    "moment": "^2.22.1",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26",
```

**Comment by hiepxanh** [comment]
do not upgrade to firebase 5 with` angularfire2 rc7 `below

**Comment by hiepxanh** [comment]
everything work normal with `angular 6` ,  `firebase 5.1.0` and `angularfire2 rc 11`

**Comment by stann84** [comment]
i have same probleme and also
 npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\stann\.config

is it a probleme to have npm update failed all time ?

**Comment by ArthurianX** [comment]
I just realized, after trying my hand at this error for the past few days ...  no matter what version combination I tried the errors were the same. 

I realized I still had `@types/firebase` installed, read about it, found out it's deprecated, and now `firebase 5.1.0` and ` angularfire2  -rc11` works perfect.

**Comment by hiepxanh** [comment]
@ArthurianX Art haha, good to know that.
@naveen-me is it work now sir?

**Comment by apamies** [comment]
For this issue I executed 
"npm dedupe"  
then uninstall and reinstall the exact version of firebase and angularfire2 (in my setup was: firebase@4.12.1  &&  angularfire2@5.0.0-rc.6.0) and this issue was solved.

**Comment by schankam** [comment]
The last firebase version is breaking things (5.3.0). Stay below that for now until the issue get fixed..

**Comment by cstodor** [comment]
Same issue with:
angularfire2 ^5.0.0-rc.3
firebase 4.11.0
rxjs 5.5.11

**Comment by hiepxanh** [comment]
@cstodor you should upgrade your firebase to new version.
@naveen-me can we close this issue?

**Comment by fdambrosio** [comment]
I have the same problem

**Comment by hiepxanh** [comment]
update your firebase to `angular 6` ,  `firebase 5.1.0` and `angularfire2 rc 11`

**Comment by jamesdaniels** [comment]
If you were compiling for SSR or in an environment that was otherwise using CJS, you could see these failures prior to rc.12. It should be addressed now.

**Comment by schankam** [comment]
"angularfire2": "^5.0.1",
"firebase": "^5.4.2"

And still getting issues.

I can for example use auth() by importing it that way:

import { auth } from 'firebase';

But then I get this warning message in my console:

It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.


Trying to import auth and only auth in so many different ways mentionned [here ](https://www.npmjs.com/package/firebase) never worked for me. Really wondering when will this package work the way it is supposed to...

**Comment by juniordevs** [comment]
> 5.0.0-rc.6

This works for me, thanks a lot.

**Comment by manisoft83** [comment]
Worked for me with these combinations,

"angularfire2": "^5.0.0-rc.6",
"firebase": "^5.1.0",
"rxjs": "^6.1.0",

**Comment by NDMCreative** [comment]
+1

**Comment by JonaSoft** [comment]
Hola espero les sirva pero yo hice lo siguiente 
npm audit, para hallar y actualizar las vulnerabilidades 
npm update, para actualizar una dependencia especifica ejemplo
 npm update firebase.
Saludos.

**Comment by jersonjcnt** [comment]
Width  Angular 7
`nce>npm install firebase angularfire2@5.0.0-rc.9 --save`

**Comment by jaimbox** [comment]
This works for my: "import * as firebase from 'firebase/app';"

**Comment by vishalchavanvicky** [comment]
I was gone through same problem solved after lot efforts. It is because of npm version is not compatible with gprc version.
So we need to update the npm.


1 - npm update
2 - npm install 

this solve my issue.
Thank you

**Comment by AhsanSN** [comment]
Worked for me with these combinations,

"angularfire2": "^5.0.0-rc.6",
"firebase": "^5.1.0",
"rxjs": "^6.1.0",

**Comment by SathyaMol93** [comment]
I found the solution, if you import from angular/firebase only this occurs, I think this is a compatibility issue with versioning. 

import {AngularFireModule} from 'angularfire2';
import {AngularFireDatabaseModule} from 'angularfire2/database';

I imported like this then the error didn't occur.

**Comment by sansan88** [comment]
https://ionicframework.com/docs/angular/pwa

**Comment by rahrl** [comment]
i have this problem 

**e**rror TS2694: Namespace '"C:/Users/mo-ro/code/myApp/node_modules/firebase/index"' has no exported member 'User'.

9 user:Observable<firebase.User>**

en my package.json is

"dependencies": {
    "-": "0.0.1",
    "@angular/animations": "~10.1.4",
    "@angular/common": "~10.1.4",
    "@angular/compiler": "~10.1.4",
    "@angular/core": "~10.1.4",
    "@angular/fire": "^6.0.4",
    "@angular/forms": "~10.1.4",
    "@angular/localize": "~10.1.4",
    "@angular/platform-browser": "~10.1.4",
    "@angular/platform-browser-dynamic": "~10.1.4",
    "@angular/router": "~10.1.4",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "angularfire2": "^5.4.2",
    "bootstrap": "^4.5.3",
    "firebase": "^8.0.0",
    "firestore-models": "^1.6.3",
    "rxjs": "~6.6.0",
    "save": "^2.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1100",
    "@angular-devkit/build-angular": "~0.1001.4",
    "@angular/cli": "^10.1.7",
    "@angular/compiler-cli": "~10.1.4",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "open": "^7.0.3",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}


what is the problem please
                           ~~~~**

**Comment by jamesdaniels** [comment]
@rahrl please don't spam questions.

**Comment by rahrl** [comment]
Hello
I use github for the first time
How i dont spam the questions
And what must i do for my problem

Thxxx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rahrl** [comment]
I install

npm install firebase angularfire2@5.0.0-rc.9 --save

And this dont solve the problem
Wat must i do

**Comment by jamesdaniels** [comment]
If you want to rollback Firebase `npm install firebase@^7.0.0`

**Comment by whoiscarlo** [comment]
The fix that I found for this is to use: **firebase.default.auth** instead of firebase.auth

**Comment by Darrow8** [comment]
For me simply closing my vscode and reopening it made the error in the linter go away.

**Comment by ramfattah** [comment]
> The fix that I found for this is to use: **firebase.default.auth** instead of firebase.auth

I confirm this is working as of firebase version 8.6.4.

Thanks Carlo!

**Comment by shareef99** [comment]
> The fix that I found for this is to use: **firebase.default.auth** instead of firebase.auth

Thanks It work for me
