### ISSUE TITLE
signInWithCredential error code auth/network-request-failed

### ISSUE THREAD

**Issue by uzumakinaruto123** [angular/angularfire2#581]
### Version info

**Angular:** 2.0.0-rc4

**Ionic:** 2.0.0-beta.35

**Firebase:** 3.3.0

**AngularFire:** 2.0.0-beta.2

Google plus sign in using `signInWithCredential(idToken)`  .

```
var provider = (<any> firebase.auth.GoogleAuthProvider).credential(null,res.idToken);

     firebase.auth().signInWithCredential(provider)
      .then((success) => {
        this.navCtrl.setRoot(TabsPage);
        console.log("Firebase success: " + JSON.stringify(success));
      })
      .catch((error) => {
        this.error = error
        console.log("Firebase failure: " + JSON.stringify(error));
      });
```

Google sign is sucessfull and idToken is received. But , it gives `404 (Not Found)` on `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=<My-Api-Key>` at `firebase.auth().signInWithCredential()` method.
### Debug output

*\* Errors in the JavaScript console **

```
POST 
https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=My-key 404 (Not Found)                                      zone.js:101

Firebase failure: {"code":"auth/network-request-failed","message":"A network error (such as timeout, interrupted connection or unreachable host) has occurred."}       app.bundle.js:254
```
### Expected behavior

Should sign in into firebase using google sign in access token.

**Comment by katowulf** [comment]
How often does this occur? Every time? 10% of the time? How many attempts did you make and over white time period? Can you upgrade to the latest (currently 3.4.0) and try again? If it's still an issue, we'll probably need a jsfiddle or plunkr that reproduces this to be much help, and it's probably not AngularFire-related.

**Comment by otherjohn** [comment]
I am getting the same behavior happen. But I don't know what do to put it on plunkr or jsfiddle.
I used this tutorial though: https://playcode.org/getting-started-with-ionic-2-rc0-firebase-3-angularfire-2/

https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=MYKEYWASHERE Failed to load resource: the server responded with a status of 404 ()

XMLHttpRequest cannot load https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=MYKEYWASHERE. Response for preflight has invalid HTTP status code 404

R {code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."}

**Comment by otherjohn** [comment]
Damn, right after posting I decided to try loading the code in firefox instead of google chrome. I didn't have an issue!  This is a Google Chrome issue. 
Aggh. I can't believe I wasted so much time on this.

**Comment by katowulf** [comment]
Nice! Well that's a useful note. It's at least a starting point for a fix. What's the minimal code needed to reproduce this? Can it be recreated with vanilla Firebase or only if AngularFire is involved? If we can whittle down the scope just a bit more, I can start looking for a solution.

**Comment by otherjohn** [comment]
I have the following via localhost:8100:
// stripped out unnecessary code


The login page has a click action called loginUser()
Error happens on clicking the loginUser.
login.ts page
```
import {AngularFire, AuthProviders, AuthMethods} from "angularfire2";

@Component({
    selector: 'page-login',
    templateUrl: 'template.html'
})
export class LoginPage {
    user = {email: 'myemail@domain.com', password: 'mypass'}; // used for testing
    constructor(private af: AngularFire) { }
    loginUser(){
         this.af.auth.login(this.user,{
             provider: AuthProviders.Password,
             method: AuthMethods.Password
         }).then((user)  => {
            console.log('user',user);
        }).catch((error) => {
            console.error(error);
        });
    }
}
```

In firefox it works just fine. In google chrome (Version 53.0.2785.143 (64-bit)) Mac, it does not.

**Comment by otherjohn** [comment]
Restart fixed the issue on google chrome.

**Comment by uzumakinaruto123** [comment]
I actually updated my Ionic to final version of angular 2 and also updated angularfire2 firebase.  The issue was not present in the updated version , so I couldn't  reproduce it.

**Comment by kleeb** [comment]
I am having the same with all updated libraries, but only on iOS native.
Tried custom auth and anonymous. All work for Android native, as well as webapp chrome, firefox and Safari. Only failing on iOS (tried iOS 9 and 10 + simulator).

Ionic 2.0.0-rc.1
angular 2.0.0
firebase 3.5.1
angularfire2 2.0.0-beta.5

**Comment by hughred22** [comment]
I am also on Ionic 2.0.0-rc.1. I notice error as below: 
<img width="659" alt="screen shot 2016-10-31 at 5 10 55 pm" src="https://cloud.githubusercontent.com/assets/2126155/19875888/f5cd5072-9f8d-11e6-88ba-e2bfb4225b37.png">

I already logged in with Google OAuth. It is when I refresh the google chrome browser and see this error. And it is not all the time. It is like 60% of the time when I refresh the browser. I see this. And this is pretty recent as well. Now sure why....

**Comment by ikabod-bubwit** [comment]
Hi, 
I have had the same problem with **signInWithCredential** which returns an error code auth/network-request-failed on Android, I have yet to test on IOS.
* firebase#3.1.0
* angularfire#2.0.1
* angular#1.5.3
* ionic#1.3.1

I am posting how I fixed my issue here to hopefully provide a possible solution to someone who may be experiencing the same issue. I have 2 identical ionic projects with the same exact versions of the previously mentioned libraries. The prototype project with the working **signInWithCredential** which I use to develop new features and my main project. The code in the main project is an exact copy and paste of my previous project yet my main project was having this issue.
I found that I had the **cordova-plugin-whitelist** installed on my prototype project.
Installing  **[cordova-plugin-whitelist](http://stackoverflow.com/questions/30161952/ionic-angular-how-to-avoid-the-404-not-found-from-cache-after-post-reque)** in my main project and adding the following lines on my config.xml file fixed my issue. 
```

<!-- Don't block any requests -->
<access origin="*" />
<!-- or -->
<access origin="https://*.googleapis.com" />
```

**Comment by hughred22** [comment]
@ikabod-bubwit Try your fix and it is not helping on Chorme browser situation (I have not tested on iOs yet). Whitelist plugin is only in Cordova situation NOT in ionic server. I am in Ionic RC2 now and still same problem. The error show up like 80% of the time when hard refresh. Please help!

**Comment by wilsoncx** [comment]
Has anyone managed to solve this problem, I have the same problem in my ionic 2 app

**Comment by dcinadr** [comment]
I am also getting this same issue.  Any solutions??

**Comment by uzumakinaruto123** [comment]
I am facing this again ! Time to reopen I guess...

**Comment by dcinadr** [comment]
I should note that this only happens when I have dev tools open in chrome.

**Comment by joshgarwood** [comment]
This is also an issue for me in Ionic RC4 using the latest firebase version

**Comment by uzumakinaruto123** [comment]
I tried it twice , and can confirm we dont get this error on f`irebase : 3.6.1`  version 3.6.5 still has the issue.

So , use version 3.6.1

**Comment by gopchi** [comment]
Still, does not work even with firebase 3.6.1. I tried running the app in Firefox or Edge and it worked nicely. I don't know what is causing this.

**Comment by dcinadr** [comment]
angularfire2 dependency for firebase is v3.3.0

**Comment by gopchi** [comment]
@dcinadr  This really did the job mate, thanks a lot!

**Comment by apatton724** [comment]
For anyone using firebase and phonegap/cordova, I ran into the same issue.

Using firebase version 3.6.1 **fixed** the issue for me.

**Comment by zwhitchcox** [comment]
This happens for me too on Chrome, even if I'm using 3.6.1 of firebase. However, it works on firefox

**Comment by zwhitchcox** [comment]
@dcinadr I don't think it has to do with angularfire, it has to do with firebase itself. I'm using react and still getting the error.

**Comment by zwhitchcox** [comment]
Even using 3.3.0 didn't fix it. Combine this with the fact Google doesn't provide a forgot password method without implementing your own server, which kind of defeats the purpose (wtf??), and this is completely unusable. Fuck.

**Comment by katowulf** [comment]
We do love feedback, and appreciate it. But please keep it productive and on topic.

**Comment by zwhitchcox** [comment]
Holy shit what a bunch of fucking morons.

**Comment by gerhardcit** [comment]
@apatton724 I can confirm this. I use 
angular#1.5.8
ionic#1.3.2
firebase#3.6.1 
angularfire#2.3.0

with firebase#3.6.6, when using $firebaseAuth().$signInWithCustomToken on and Android app (6.0 and 4.4)  I get the ```"auth/network request failed``` even though I have already logged a connection info to the firebase db.
This does NOT happen in a browser, or on iOS (same app) only Android app.
There seem to be something wrong with the timing of sign-in of firebaseAuth.

if you watch $firebaseAuth.$onAuthStateChanged  you will see it fires twice when you use
$firebaseAuth().$signInWithCustomToken.
Once without a firebaseUser and once with the actual signed in user. (Ver 3.6.1)
In ver 3.6.5 and 3.6.6  the 2nd $onAuthStateChanged does NOT fire.

**Comment by katowulf** [comment]
Can you reproduce the same behavior without AngularFire, by dropping to the Firebase SDK and running auth?

**Comment by whispyy** [comment]
also have the same issue, i tried this following : 
- add cordova-whitelist-plugin
- check meta content-security-policy
- remove <form> balise

using :
ionic#1.3.1
firebase#3.6.6

**Comment by satyagupta** [comment]
why was it closed? there are many still facing the same issue. It works only 20% else it would keep showing network error.

**Comment by katowulf** [comment]
Checked up on this today with the auth team and they pointed out this interesting fix in the [3.6.8 release](https://firebase.google.com/support/release-notes/js#3.6.8):

![image](https://cloud.githubusercontent.com/assets/959972/22720602/f2292634-ed68-11e6-9989-050115cbc8b6.png)

Could someone test this out and verify that it's fixed in 3.6.8 of the Firebase SDK? I think that will resolve many of the reports here.

**Comment by satyagupta** [comment]
@katowulf update firebase to latest 3.6.9 and still facing the same issue :(

**Comment by dcinadr** [comment]
@satyagupta is correct.  It still does not work.  I am using it with Ionic2 which requires angular 2.2.1.  This requires me to use angularfire2 no later than v2.0.0-beta.6.  I am not sure if this causes an issue.  Cause I have another project that uses the latest angularfire2 and the latest angular (not an ionic project) and there is no problems on that project.

**Comment by satyagupta** [comment]
@dcinadr can you share the version/specs of other project where it works? i ahve been trying a lot of things but its does not fix it.

**Comment by katowulf** [comment]
For the "does not work" replies, please open a new issue, with more specific errors/stacks/details and minimal repros, as well as networking logs. To move this forward, we'll need to build a strong case here showing that this is an issue in the SDK and not related to the many other moving parts in an Ionic build.

**Comment by dcinadr** [comment]
@satyagupta - here are my dependencies
```
"dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "@angular/upgrade": "2.4.3",
    "@types/lodash": "4.14.50",
    "angular-calendar": "0.6.2",
    "angular2-datatable": "0.5.2",
    "angular2-ladda": "^1.0.6",
    "angular2-toaster": "2.0.0",
    "angularfire2": "2.0.0-beta.7",
    "chart.js": "^2.3.0",
    "core-js": "^2.4.0",
    "dragula": "^3.7.2",
    "firebase": "^3.6.9",
    "moment": "2.17.1",
    "ng2-bootstrap": "^1.2.5",
    "ng2-charts": "^1.5.0",
    "ng2-dragula": "^1.3.0",
    "ng2-select": "^1.2.0",
    "rxjs": "5.0.3",
    "ts-helpers": "^1.1.2",
    "zone.js": "0.7.6"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.41",
    "angular-cli": "1.0.0-beta.25.5",
    "codelyzer": "2.0.0-beta.4",
    "extract-text-webpack-plugin": "^2.0.0-rc.0",
    "gulp": "^3.9.1",
    "gulp-sass": "^3.1.0",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-remap-istanbul": "^0.4.0",
    "protractor": "5.0.0",
    "ts-node": "2.0.0",
    "tslint": "4.3.1",
    "typescript": "2.1.5"
  }
```

**Comment by satyagupta** [comment]
`"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "^1.1.7",
    "angularfire2": "^2.0.0-beta.7",
    "autolinker": "^1.4.0",
    "crypto-js": "^3.1.9-1",
    "firebase": "^3.6.6",
    "font-awesome": "^4.7.0",
    "ionic-angular": "2.0.0-rc.5",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "localforage": "^1.4.3",
    "rxjs": "^5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "typescript": "^2.0.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  }`

here is mine, i had to down grade the firebase and angular fire to make it work.

BTW i keep getting error that Angular needs rxjs 5.0.0 if i do `npm update`

**Comment by dcinadr** [comment]
@satyagupta - i believe the problem is with ionic2.  It doesn't support the latest version of angular.  thats why this project works for me.  Because it is not an ionic project.  When I use it my ionic project i am getting the same problems as you.

**Comment by satyagupta** [comment]
oh k so you are using it as a AngularProject right?

**Comment by uzumakinaruto123** [comment]
@katowulf  check dependencies posted by @dcinadr above.  That project does not even include ionic.

Debug output has been included in the OP (by me). That is complete js error that is thrown everytime. 

Maybe I will post again ,


Google sign is sucessfull and idToken is received. But , it gives `404 (Not Found)` on `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=<My-Api-Key>` at `firebase.auth().signInWithCredential()` method.
### Debug output

*\* Errors in the JavaScript console **

```
POST 
https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=My-key 404 (Not Found)                                      zone.js:101

Firebase failure: {"code":"auth/network-request-failed","message":"A network error (such as timeout, interrupted connection or unreachable host) has occurred."}       app.bundle.js:254
```



What can be more specific ? I will post if I can

Thanks

**Comment by satyagupta** [comment]
@uzumakinaruto123 bro create a new ticket with same details. 

And i confirm the same issue that we face too. verifyPassword works but then the next request does not goes through and same error throws.

**Comment by kleeb** [comment]
angularfire2 beta.7 requires rxjs ^5.0.1, however angular 2.2.1 beta 12
there are more mismatches with versioning that may produce some bugs

**Comment by dcinadr** [comment]
I believe the root of the problem is that ionic-angular requires us to us v2.2.1.  And if we want to update angularfire2 and firebase to a version that doesn't produce this bug it requires us to update rxjs.  And if we update rxjs than angular v2.2.1 is not compatible.  And since ionic-angular requires us to us v2.2.1 we can not update rxjs.  So we have a circular problem that requires us to use older versions that will not solve this problem until ionic updates the version of angular that they are using.  I have reached out to ionic and they have not responded with an update yet.

**Comment by satyagupta** [comment]
Which is why i had to downgrade the version of firebase after i updated it to 3.6.9.

I just wonder why others are not responding to this issue since many should be facing this very problem!! and why was this issue closed?

**Comment by dcinadr** [comment]
People that are experiencing it are probably just working around it since it is not a show stopper.  You can use another browser or you can skip the message or you can load your dev tools after the app is loaded.

**Comment by satyagupta** [comment]
Any code snippets would be very helpful @dcinadr we are stuck with this app where most of the part is ready but we cannot test on device :(

**Comment by kleeb** [comment]
Switching to rxjs >= 5 is not breaking anything. Npm is showing some dependency warnings, but not errors. Ionic team is fully aware about it, they are even using rxjs version 5 in the alpha version of the new ionic-native, so I guess the final release is a matter of time.

**Comment by Qyoom** [comment]
Please, why does this issue keep getting closed? What is the resolution? I can create a Firebase account with email/password in Firefox, but not with Chrome (Dev Tools off). Just straight up web, not Ionic. @dcinadr what is the work around you refer to? I do not have DevTools open in Chrome and get the network error. I'm using the code straight out of the documentation:

this.auth.createUserWithEmailAndPassword(email, password).catch(function(error) {
            // Handle Errors here.
            var errorCode = error.code;
            var errorMessage = error.message;
            // ...
            console.log("createUserWithEmailAndPassword errorCode: " + errorCode);
            console.log("createUserWithEmailAndPassword errorMessage: " + errorMessage);
        });

ERROR:
createUserWithEmailAndPassword errorCode: auth/network-request-failed
createUserWithEmailAndPassword errorMessage: A network error (such as timeout, interrupted connection or unreachable host) has occurred.

**Comment by dcinadr** [comment]
@Qyoom - please refer to my previous post for my workarounds.  However, you are running a command that I am not running yet.  So it is possible that my workaround will not work for you.  And I may run into the same problem you are experiencing once i use that command.

**Comment by nilebma** [comment]
Hi everyone ! 

I have this problem with Ionic 2 on Android Phones below KitKat (<4.4), even with crosswalk plugin installed. I use theses versions :

**Ionic 2.1.0**
**Angular 2.2.1** (this version is mandatory for Ionic 2.1.0)
**Rxjs 5.0.1 or 5.0.0-beta.12**  (both tested)

If anyone have a clue on how to fix this, that would be greatly appreciated ! :-)

**Comment by AlvaroHerrero** [comment]
Fixed using firebase 3.6.1 with this configuration
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7

**Comment by dovk** [comment]
Could someone from the Ionic or AngularFire team please show some direction - perhaps publish the package.json that has been verified to work with the latest versions of AngularFire2+Ionic2. If this could be done every time you put out a new version, it would save so many people so much time and pain. I have spent the past week trying to move to Ionic 2.2, the email authentication stopped working on Android.
What is wrong with this ?

"dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/core": "3.1.0",
    "@ionic-native/splash-screen": "3.1.0",
    "@ionic-native/status-bar": "3.1.0",
    "@ionic/storage": "2.0.0",
    "angularfire2": "^2.0.0-beta.8",
    "chart.js": "^2.5.0",
    "datepicker-ionic2": "^2.2.2",
    "firebase": "3.7.3",
    "ionic-angular": "2.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.2.2",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-statusbar",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
(I also tried the different firebase version like 3.6.1...)

**Comment by patel1jr** [comment]
changing the type in my button tag to type="button" instead of type="submit" solved this problem for me.

**Comment by nilebma** [comment]
Thanks for sharing your solutions @patel1jr  and @AlvaroHerrero . Unfortunately, none of them works on my side. I tried every updates since I encounter the problem more than a month ago, but it persists : impossible to log or signup users on Android < 4.4 ...  :-/

**Comment by dovk** [comment]
Of all of the suggestions above, the one thing that worked eventually was using "**firebase": "3.0.0**" instead of "firebase": "3.7.3" in package.json (enclosed a few posts before). 
I'm using a very basic login based on an example from Jorge Vergara 
https://javebratt.com/angularfire2-authentication-ionic/

Too bad this is the current situation - well, Good Luck to all of us!

**Comment by wilsoncx** [comment]
I solved this problem by entering the manifest.xml file and putting this line <uses-permission android: name = "android.permission.INTERNET" />

**Comment by AbdullahAdeeb** [comment]
I'm facing the same issue building Ionic2/AngularFire2 app and also with Ionic2/Firebase sdk.
It works fine with serve on chrome and firefox but issue occurs with run on browser or android (i.e. ionic run android) or run using cordova is essentially the same. Therefore, it seems like its an issue  with cordova and firebase.

Those are my dependencies: 
cordova@6.3.1
firebase@3.7.5
angularfire2 @2.0.0-beta.7-pre
angular@2.4.8
ionic-angular@2.3.0
ionicons@3.0.0
rxjs@5.0.1
sw-toolbox@3.4.0
typescript@2.0.9
ionic@2.2.1

**Thanks to the folks here, I was able to fix it by downgrading to firebase@3.6.1 and now its working fine on android.**

**Comment by kleeb** [comment]
I feel that the most stable Firebase version with angularfire2 beta8 is 3.4.0

**Comment by dovk** [comment]
I have meanwhile moved up to Ionic3/Angular4 and all is well except for having to keep Firebase
at **3.3.0** (I tried Firebase@3.4.0 as mentioned above but it did not work).
You can see my package.json here https://github.com/dovk/ionic3-calendar
(and if anyone is looking for a simple Calendar/Datepicker - feel free to use it)

**Comment by lawlesscreation** [comment]
+1 for rolling back to Firebase 3.3.0. I've been having a problem with intermittent connections to Firebase on Android devices. But rolling back seems to have resolved the issue.

**Comment by gammafilho** [comment]
downgrade from 3.7.5 to 3.3.0 works for me.

**Comment by burnettejl** [comment]
I've been trying to fix this ionic/firebase issue on my android device for 2 days straight. Worked great in browser but not on android device. Downgrading to 3.3.0 did the trick. If only I found this faster -__- Thanks!

**Comment by deoxen0n2** [comment]
Hi, I'm also using ionic. I can reproduce this 100% of the time on my phone (also tested on Firefox and Chrome desktop, but never encounter this problem). `cordova-plugin-whitelist` is configured and has been worked in the past. I experimented a lot, the steps to reproduce is like this:

From Android phone:

1. Use login form with login button, with or without `ngSubmit`, does not matter
2. Tap and enter email and password
3. While device keyboard is still opened, press enter (big right arrow on some keyboards) or the login button and `auth/network-request-failed` will be thrown
4. Tap somewhere else to close the keyboard, press the login button and `auth/network-request-failed` will be thrown again
5. Tap into email or password input, press enter (big right arrow on some keyboards) or the login button and now it will log in successfully

It should has nothing to do with the keyboard or input focus / refocus but I don't have any clue either.

Finally I tried downgrading to 3.3.0 and it solved the issue. But this should not be an acceptable workaround.

I think we should also try the recent Firebase SDK 4.0.0 and since it is open sourced it should be easier to debug (https://github.com/firebase/firebase-js-sdk). I will try and if the problem still persist I think we should open the new issue there.

**Comment by brunolemos** [comment]
I have this issue with 0.5% of the user requests, which is low but that's a lot of users. (using `v3.9`).
Has anyone tried `v4.0`?

**Comment by grrrian** [comment]
We are also having this issue on Android with firebase 3.9.0.

**Comment by iturn** [comment]
+1

**Comment by pvdyck** [comment]
same problem here ... inconsistent and impossible to reproduce for now.

**Comment by iturn** [comment]
In use is angularfire-4.0.0 and there is a thread here that may be the cause?
https://github.com/angular/angularfire2/issues/581

I'm thinking that with a restart of the application the offline database tries to sync before it a user login happens.

**Comment by washowasho** [comment]
Including the [cordova-plugin-network-information](https://github.com/apache/cordova-plugin-network-information) corrected this issue for me. I confirmed that the 'navigator.onLine' was occasionally 'false', which I believe was causing Firebase to think there was an issue. Once I added the cordova-plugin-network-information to my project, the problem went away. I didn't dig deep into why, but I suspect this plugin has a better wrapper around the navigator which may be giving Firebase better information. I did confirm this problem came back after removing the plugin, but re-applying it fixes it. I will update this if I dig deeper. I hope this helps.

**Comment by brunolemos** [comment]
@washowasho interesting, so in theory this should help:

```js
 Object.defineProperty(navigator, 'onLine', {
   get: function() { return true; },
   set: function() {}
 });
```

**Comment by razgriz-detroit** [comment]
@washowasho THANK YOU SO MUCH!!! Solved it for me!

**Comment by washowasho** [comment]
Looks like this may have been solved in the latest release of Firebase 4.2.0. I'll be verifying when I get a chance.

"Refactored to not use navigator.onLine for offline detection in Cordova environments."

https://firebase.google.com/support/release-notes/js#4.2.0

**Comment by cipher21** [comment]
Seems like after I downgrade firebase to 3.3.0 it is resolved. Before this I was continuously getting 'auth/network-request-failed'. Let me know if there is solution for this in newer versions.

**Comment by harishmahajan** [comment]
i tried all above solutions but not works for me

**Comment by derwaldgeist** [comment]
> Looks like this may have been solved in the latest release of Firebase 4.2.0

Unfortunately, it isn't. With 4.4.0, the problem is still there. I'm not using angularfire2, though.

**Comment by stevenyap** [comment]
I confirm that it is not working with 4.4.0 but downgrading to 3.3.0 works for me

**Comment by derwaldgeist** [comment]
I got it working by adding `cordova-plugin-network-information` to my Cordova app. Downgrading to 3.3.0 did not help, since I need phone number auth.

**Comment by nomood89** [comment]
I have faced the same issue, and i tried most of the solution above (including downgrade to firebase 3.3.0 or add cordova-plugin), and none of them work for me.

I'm currently using firebase 4.4.0. I was able to fix the problem by adding the line below.

**Comment by derwaldgeist** [comment]
I already had this permission in my app. Still, the logon did not work reliably. The only solution I found was to either add the plugin mentioned above or override `navigator.onLine` to return `true` every time it is being called. This solved the problem as well, but seemed to be a too weird hack, especially if another plugin relies on this getter variable.

**Comment by dovk** [comment]
Can you show the code you added regarding the network plugin and where you added it? I want to check it makes things more stable. Thanks

**Comment by derwaldgeist** [comment]
It's this Cordova plugin: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-network-information/, but this would only make sense if you're building a Cordova application.

However, what it basically does (that fixes the Firebase problem) is to override the navigator.onLine getter. You could achieve the same "fix" with this code:

```js
  Object.defineProperty(navigator, 'onLine', {
      get: function() {
        return true;
      },
      set: function() {}
    });
```

But beware this overrides the standard `navigator` property `onLine` with a monkey-patch and thus may break other code that relies on this information. The aforementioned Cordova plugin does more than this, it uses actual native code to implement `navigator.onLine`.

The main reason why Firebase auth fails is that it relies on `navigator.onLine` returning a correct connection status. My phone - as many others - report it as `false`, however, even if there's a working connection. I have no clue why this happens.

**Comment by Luiz-N** [comment]
I'm not using angularfire but I am on firebase 4.4.0 and seeing this issue trying to use auth via with `onAuthStateChanged` and `onIdTokenChanged` listeners in election (an atom package specifically). I believe it was after adding the `onIdTokenChanged` listener and then closing my laptop and opening it up again a few hours later to see my screen flooded with this error. My guess is this has to do with my mac waking itself up periodically which establishes an internet connection but then going back to sleep which is confusing firebase.

**Comment by hiepxanh** [comment]
the same issue :(

**Comment by katowulf** [comment]
@hiepxanh "library was not found" is by no means the "same issue" as "auth/network-request-failed". Please submit a new issues.

Folks, this is a closed issue. Locking this issue to encourage value-add contributions over more "me too" and "does not work replies. Please open a new issue if you think you have done sufficient due diligence to show a bug with this lib, including specific errors/stacks/details and minimal repros with complete and minimal code/versions/sample data required to run them. Always include networking logs for issues like this as well.
